name: Refresh Github Actions Cache

on:
  schedule:
    - cron: '0 11 */6 * *'

jobs:
  refresh_cache:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Refresh ccache
      uses: actions/cache@main
      with:
        path: ${{ github.workspace }}/openwrt/.ccache
        key: ccache-amlogic-${{ env.week }}-${{ env.hash }}
        restore-keys: ccache-amlogic-
